<?php
/**
 * @var \Bluz\View\View $this
 */
?>
<h3 class="page-header">
    <?=__('Reply page')?>
</h3>
<a href="<?=$this->url('contactUs', 'grid')?>">Back to grid</a>
<dl class="dl-horizontal">
    <dt><?=__('Name')?></dt>
    <dd><?=$row['name']?></dd>
    <br />
    <dt><?=__('Email')?></dt>
    <dd><?=$row['email']?></dd>
    <br />
    <dt><?=__('Message')?></dt>
    <dd>[<?=$row['created']?>]</dd>
    <dd><?=$row['message']?></dd>
    <br />
    <dt><?=__('Reply')?></dt>
    <dd>
        <form class="form-horizontal ajax" method="post" action="<?=$this->url('contactUs', 'reply')?>" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="id" value="<?=$row['id']?>">
            <div class="form-group">
                <div class="col-lg-6">
                    <textarea rows="5" cols="10" id="content" class="form-control redactor" name="message" required ></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-6">
                    <button type="submit" class="btn btn-primary"><?=__('Reply')?></button>
                </div>
            </div>
        </form>
    </dd>
</dl>